// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: protobuf/state.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type State struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to State:
	//
	//	*State_V1
	State isState_State `protobuf_oneof:"state"`
}

func (x *State) Reset() {
	*x = State{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_state_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_state_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_protobuf_state_proto_rawDescGZIP(), []int{0}
}

func (m *State) GetState() isState_State {
	if m != nil {
		return m.State
	}
	return nil
}

func (x *State) GetV1() *StateV1 {
	if x, ok := x.GetState().(*State_V1); ok {
		return x.V1
	}
	return nil
}

type isState_State interface {
	isState_State()
}

type State_V1 struct {
	V1 *StateV1 `protobuf:"bytes,1,opt,name=v1,proto3,oneof"`
}

func (*State_V1) isState_State() {}

type StateV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OffsetProgress map[int32]int64 `protobuf:"bytes,1,rep,name=offset_progress,json=offsetProgress,proto3" json:"offset_progress,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *StateV1) Reset() {
	*x = StateV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_state_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateV1) ProtoMessage() {}

func (x *StateV1) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_state_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateV1.ProtoReflect.Descriptor instead.
func (*StateV1) Descriptor() ([]byte, []int) {
	return file_protobuf_state_proto_rawDescGZIP(), []int{1}
}

func (x *StateV1) GetOffsetProgress() map[int32]int64 {
	if x != nil {
		return x.OffsetProgress
	}
	return nil
}

var File_protobuf_state_proto protoreflect.FileDescriptor

var file_protobuf_state_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a,
	0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x02, 0x76, 0x31, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x56, 0x31, 0x48, 0x00, 0x52, 0x02, 0x76, 0x31, 0x42, 0x07, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x22, 0x99, 0x01, 0x0a, 0x07, 0x53, 0x74, 0x61, 0x74, 0x65, 0x56, 0x31, 0x12, 0x4b, 0x0a,
	0x0f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x56, 0x31, 0x2e, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x50, 0x72, 0x6f,
	0x67, 0x72, 0x65, 0x73, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0e, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x1a, 0x41, 0x0a, 0x13, 0x4f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x22, 0x5a,
	0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x6a, 0x77, 0x61,
	0x6c, 0x74, 0x2f, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_state_proto_rawDescOnce sync.Once
	file_protobuf_state_proto_rawDescData = file_protobuf_state_proto_rawDesc
)

func file_protobuf_state_proto_rawDescGZIP() []byte {
	file_protobuf_state_proto_rawDescOnce.Do(func() {
		file_protobuf_state_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_state_proto_rawDescData)
	})
	return file_protobuf_state_proto_rawDescData
}

var file_protobuf_state_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protobuf_state_proto_goTypes = []interface{}{
	(*State)(nil),   // 0: proto.State
	(*StateV1)(nil), // 1: proto.StateV1
	nil,             // 2: proto.StateV1.OffsetProgressEntry
}
var file_protobuf_state_proto_depIdxs = []int32{
	1, // 0: proto.State.v1:type_name -> proto.StateV1
	2, // 1: proto.StateV1.offset_progress:type_name -> proto.StateV1.OffsetProgressEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protobuf_state_proto_init() }
func file_protobuf_state_proto_init() {
	if File_protobuf_state_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_state_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*State); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_state_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protobuf_state_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*State_V1)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_state_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_state_proto_goTypes,
		DependencyIndexes: file_protobuf_state_proto_depIdxs,
		MessageInfos:      file_protobuf_state_proto_msgTypes,
	}.Build()
	File_protobuf_state_proto = out.File
	file_protobuf_state_proto_rawDesc = nil
	file_protobuf_state_proto_goTypes = nil
	file_protobuf_state_proto_depIdxs = nil
}
